# Generated by Django 4.0.6 on 2022-08-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('boat_type', models.CharField(choices=[('M', 'Motorboat'), ('C', 'Cabin cruiser'), ('D', 'Dinghy'), ('K', 'Keel boat')], max_length=32)),
                ('location', models.CharField(max_length=64)),
                ('has_motor', models.BooleanField()),
            ],
        ),
    ]
