# Generated by Django 4.1 on 2023-03-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "membergroup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="groups.membergroup",
                    ),
                ),
                ("year", models.IntegerField(default=56)),
            ],
            bases=("groups.membergroup",),
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "membergroup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="groups.membergroup",
                    ),
                ),
                (
                    "mandatory",
                    models.BooleanField(
                        default=False,
                        help_text="If this is checked new members should be assigned to this committee, any members that are part of this committee satisfy their committee_duty.",
                    ),
                ),
            ],
            bases=("groups.membergroup",),
        ),
        migrations.CreateModel(
            name="Fraternity",
            fields=[
                (
                    "membergroup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="groups.membergroup",
                    ),
                ),
                (
                    "gender_requirement",
                    models.CharField(
                        choices=[
                            ("MIXED", "Mixed"),
                            ("FEMALE", "Female"),
                            ("MALE", "Male"),
                        ],
                        default="MIXED",
                        max_length=6,
                    ),
                ),
            ],
            bases=("groups.membergroup",),
        ),
        migrations.CreateModel(
            name="YearClub",
            fields=[
                (
                    "membergroup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="groups.membergroup",
                    ),
                ),
                ("year", models.IntegerField(default=56)),
            ],
            bases=("groups.membergroup",),
        ),
    ]
