# Generated by Django 4.0.6 on 2022-08-06 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemembership',
            name='note',
            field=models.CharField(blank=True, default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='since',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
