# Generated by Django 4.0.6 on 2022-08-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_alter_committeemembership_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemembership',
            name='since',
            field=models.DateField(),
        ),
    ]
