# Generated by Django 4.0.6 on 2022-07-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='relation_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
