# Generated by Django 4.1 on 2022-08-22 16:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.generic.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                (
                    "is_open_event",
                    models.BooleanField(
                        default=False, help_text="Event is open for non-members"
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="start time")),
                ("end", models.DateTimeField(verbose_name="end time")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("alumni", "Alumni"),
                            ("leisure", "Leisure"),
                            ("association", "Association Affairs"),
                            ("sailing", "Sailing"),
                            ("competition", "Competition"),
                            ("other", "Other"),
                        ],
                        help_text="Alumni: Events organised for alumni, Leisure: borrels, parties, game activities etc., Association Affairs: general meetings or any other board related events, Sailing: sailingCompetition: NESTOR, Regatta's etcOther: anything else.",
                        max_length=40,
                        verbose_name="category",
                    ),
                ),
                (
                    "registration_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="If you set a registration period registration will be required. If you don't set one, registration won't be required. Prefer times when people don't have lectures, e.g. 12:30 instead of 13:37.",
                        null=True,
                        verbose_name="registration start",
                    ),
                ),
                (
                    "registration_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="If you set a registration period registration will be required. If you don't set one, registration won't be required.",
                        null=True,
                        verbose_name="registration end",
                    ),
                ),
                (
                    "cancel_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancel deadline"
                    ),
                ),
                (
                    "send_cancel_email",
                    models.BooleanField(
                        default=True,
                        help_text="Send an email to the organising party when a member cancels their registration after the deadline.",
                        verbose_name="send cancellation notifications",
                    ),
                ),
                (
                    "optional_registrations",
                    models.BooleanField(
                        default=True,
                        help_text="Participants can indicate their optional presence, even though registration is not actually required. This ignores registration start and end time or cancellation deadlines, optional registration will be enabled directly after publishing until the end of the event.",
                        verbose_name="allow optional registrations",
                    ),
                ),
                ("location", models.CharField(max_length=255, verbose_name="location")),
                (
                    "map_location",
                    models.CharField(
                        help_text="Location of Huygens: Heyendaalseweg 135, Nijmegen. Location of Mercator 1: Toernooiveld 212, Nijmegen. Use the input 'discord' or 'online' for special placeholders. Not shown as text!!",
                        max_length=255,
                        verbose_name="location for minimap",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price",
                    ),
                ),
                (
                    "fine",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fine if participant does not show up (at least €5).",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="fine",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="maximum number of participants",
                    ),
                ),
                (
                    "no_registration_message",
                    models.CharField(
                        blank=True,
                        default="No registration required",
                        help_text="Default: No registration required",
                        max_length=200,
                        verbose_name="message when there is no registration",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuestContactDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "IBAN",
                    localflavor.generic.models.IBANField(
                        blank=True,
                        include_countries=None,
                        max_length=34,
                        null=True,
                        use_nordea_extensions=False,
                    ),
                ),
                (
                    "address_street",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="please use the format <street> <number>",
                                regex="^.+ \\d+.*",
                            )
                        ],
                        verbose_name="Street and house number",
                    ),
                ),
                (
                    "address_street2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Second address line",
                    ),
                ),
                (
                    "address_postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Postal code"
                    ),
                ),
                (
                    "address_city",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "address_country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AX", "Åland Islands"),
                            ("AL", "Albania"),
                            ("AD", "Andorra"),
                            ("AT", "Austria"),
                            ("BY", "Belarus"),
                            ("BE", "Belgium"),
                            ("BA", "Bosnia and Herzegovina"),
                            ("BG", "Bulgaria"),
                            ("HR", "Croatia"),
                            ("CZ", "Czechia"),
                            ("DK", "Denmark"),
                            ("EE", "Estonia"),
                            ("FO", "Faroe Islands"),
                            ("FI", "Finland"),
                            ("FR", "France"),
                            ("DE", "Germany"),
                            ("GI", "Gibraltar"),
                            ("GR", "Greece"),
                            ("GG", "Guernsey"),
                            ("VA", "Vatican City"),
                            ("HU", "Hungary"),
                            ("IS", "Iceland"),
                            ("IE", "Ireland"),
                            ("IM", "Isle of Man"),
                            ("IT", "Italy"),
                            ("JE", "Jersey"),
                            ("LV", "Latvia"),
                            ("LI", "Liechtenstein"),
                            ("LT", "Lithuania"),
                            ("LU", "Luxembourg"),
                            ("MK", "Macedonia (FYROM)"),
                            ("MT", "Malta"),
                            ("MD", "Moldova"),
                            ("MC", "Monaco"),
                            ("ME", "Montenegro"),
                            ("NL", "Netherlands"),
                            ("NO", "Norway"),
                            ("PL", "Poland"),
                            ("PT", "Portugal"),
                            ("RO", "Romania"),
                            ("RU", "Russian Federation"),
                            ("SM", "San Marino"),
                            ("RS", "Serbia"),
                            ("SK", "Slovakia"),
                            ("SI", "Slovenia"),
                            ("ES", "Spain"),
                            ("SJ", "Svalbard and Jan Mayen"),
                            ("SE", "Sweden"),
                            ("CH", "Switzerland"),
                            ("UA", "Ukraine"),
                            ("GB", "United Kingdom"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_form",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="registration date",
                    ),
                ),
                (
                    "date_cancelled",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancellation date"
                    ),
                ),
                ("present", models.BooleanField(default=False, verbose_name="present")),
                ("paid", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "guest_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.guestcontactdetails",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "user")},
            },
        ),
    ]
