# Generated by Django 4.0.6 on 2022-08-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='no_registration_message',
            field=models.CharField(blank=True, default='No registration required', help_text='Default: No registration required', max_length=200, verbose_name='message when there is no registration'),
        ),
    ]
