# Generated by Django 4.0.6 on 2022-08-06 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_guestform'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='guest_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.guestform'),
        ),
    ]
