# Generated by Django 4.0.6 on 2022-08-06 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_alter_guestcontactdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcontactdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_form', to=settings.AUTH_USER_MODEL),
        ),
    ]
