# Generated by Django 4.0.6 on 2022-08-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='display_name_preference',
            field=models.CharField(choices=[('full', 'Show full name'), ('nickname', 'Show only nickname'), ('firstname', 'Show only first name'), ('initials', 'Show initials and last name'), ('fullnick', 'Show name like "John \'nickname\' Doe"'), ('nicklast', 'Show nickname and last name')], default='full', max_length=10, verbose_name='How to display name'),
        ),
        migrations.AddField(
            model_name='member',
            name='initials',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Initials'),
        ),
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_description',
            field=models.TextField(blank=True, help_text='Text to display on your profile', max_length=4096, verbose_name='Profile text'),
        ),
        migrations.AddField(
            model_name='member',
            name='show_birthday',
            field=models.BooleanField(default=True, help_text='Show your birthday to other members on your profile page and in the birthday calendar', verbose_name='Display birthday'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
